# Generated by Django 5.0.5 on 2024-05-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_shippingdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_num', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingdetail',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='shippingdetail',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='ShippingDetail',
        ),
    ]
